'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18408
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SrController
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SrController.IController")>  _
    Public Interface IController
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IController/TraeFacultad", ReplyAction:="http://tempuri.org/IController/TraeFacultadResponse")>  _
        Function TraeFacultad() As Models.Parametros()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IController/TraeFacultad", ReplyAction:="http://tempuri.org/IController/TraeFacultadResponse")>  _
        Function TraeFacultadAsync() As System.Threading.Tasks.Task(Of Models.Parametros())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IController/TraeEscuelaPorFacultad", ReplyAction:="http://tempuri.org/IController/TraeEscuelaPorFacultadResponse")>  _
        Function TraeEscuelaPorFacultad(ByVal idFacultad As Integer) As Models.Parametros()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IController/TraeEscuelaPorFacultad", ReplyAction:="http://tempuri.org/IController/TraeEscuelaPorFacultadResponse")>  _
        Function TraeEscuelaPorFacultadAsync(ByVal idFacultad As Integer) As System.Threading.Tasks.Task(Of Models.Parametros())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IController/TraeCarreraPorEscuela", ReplyAction:="http://tempuri.org/IController/TraeCarreraPorEscuelaResponse")>  _
        Function TraeCarreraPorEscuela(ByVal idEscuela As Integer) As Models.Parametros()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IController/TraeCarreraPorEscuela", ReplyAction:="http://tempuri.org/IController/TraeCarreraPorEscuelaResponse")>  _
        Function TraeCarreraPorEscuelaAsync(ByVal idEscuela As Integer) As System.Threading.Tasks.Task(Of Models.Parametros())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IController/TraeHistorialPorCarrera", ReplyAction:="http://tempuri.org/IController/TraeHistorialPorCarreraResponse")>  _
        Function TraeHistorialPorCarrera(ByVal idCarrera As Integer) As Models.HistorialCurricular()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IController/TraeHistorialPorCarrera", ReplyAction:="http://tempuri.org/IController/TraeHistorialPorCarreraResponse")>  _
        Function TraeHistorialPorCarreraAsync(ByVal idCarrera As Integer) As System.Threading.Tasks.Task(Of Models.HistorialCurricular())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IController/TraeAsignaturasPorHistorial", ReplyAction:="http://tempuri.org/IController/TraeAsignaturasPorHistorialResponse")>  _
        Function TraeAsignaturasPorHistorial(ByVal idHistorial As Integer) As Models.Parametros()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IController/TraeAsignaturasPorHistorial", ReplyAction:="http://tempuri.org/IController/TraeAsignaturasPorHistorialResponse")>  _
        Function TraeAsignaturasPorHistorialAsync(ByVal idHistorial As Integer) As System.Threading.Tasks.Task(Of Models.Parametros())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IControllerChannel
        Inherits SrController.IController, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ControllerClient
        Inherits System.ServiceModel.ClientBase(Of SrController.IController)
        Implements SrController.IController
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function TraeFacultad() As Models.Parametros() Implements SrController.IController.TraeFacultad
            Return MyBase.Channel.TraeFacultad
        End Function
        
        Public Function TraeFacultadAsync() As System.Threading.Tasks.Task(Of Models.Parametros()) Implements SrController.IController.TraeFacultadAsync
            Return MyBase.Channel.TraeFacultadAsync
        End Function
        
        Public Function TraeEscuelaPorFacultad(ByVal idFacultad As Integer) As Models.Parametros() Implements SrController.IController.TraeEscuelaPorFacultad
            Return MyBase.Channel.TraeEscuelaPorFacultad(idFacultad)
        End Function
        
        Public Function TraeEscuelaPorFacultadAsync(ByVal idFacultad As Integer) As System.Threading.Tasks.Task(Of Models.Parametros()) Implements SrController.IController.TraeEscuelaPorFacultadAsync
            Return MyBase.Channel.TraeEscuelaPorFacultadAsync(idFacultad)
        End Function
        
        Public Function TraeCarreraPorEscuela(ByVal idEscuela As Integer) As Models.Parametros() Implements SrController.IController.TraeCarreraPorEscuela
            Return MyBase.Channel.TraeCarreraPorEscuela(idEscuela)
        End Function
        
        Public Function TraeCarreraPorEscuelaAsync(ByVal idEscuela As Integer) As System.Threading.Tasks.Task(Of Models.Parametros()) Implements SrController.IController.TraeCarreraPorEscuelaAsync
            Return MyBase.Channel.TraeCarreraPorEscuelaAsync(idEscuela)
        End Function
        
        Public Function TraeHistorialPorCarrera(ByVal idCarrera As Integer) As Models.HistorialCurricular() Implements SrController.IController.TraeHistorialPorCarrera
            Return MyBase.Channel.TraeHistorialPorCarrera(idCarrera)
        End Function
        
        Public Function TraeHistorialPorCarreraAsync(ByVal idCarrera As Integer) As System.Threading.Tasks.Task(Of Models.HistorialCurricular()) Implements SrController.IController.TraeHistorialPorCarreraAsync
            Return MyBase.Channel.TraeHistorialPorCarreraAsync(idCarrera)
        End Function
        
        Public Function TraeAsignaturasPorHistorial(ByVal idHistorial As Integer) As Models.Parametros() Implements SrController.IController.TraeAsignaturasPorHistorial
            Return MyBase.Channel.TraeAsignaturasPorHistorial(idHistorial)
        End Function
        
        Public Function TraeAsignaturasPorHistorialAsync(ByVal idHistorial As Integer) As System.Threading.Tasks.Task(Of Models.Parametros()) Implements SrController.IController.TraeAsignaturasPorHistorialAsync
            Return MyBase.Channel.TraeAsignaturasPorHistorialAsync(idHistorial)
        End Function
    End Class
End Namespace
